export const CITIES = [
  // Australia
  'Sydney, Australia',
  'Melbourne, Australia',
  'Brisbane, Australia',
  'Perth, Australia',
  'Adelaide, Australia',
  'Canberra, Australia',
  'Gold Coast, Australia',
  'Newcastle, Australia',
  'Hobart, Australia',
  'Darwin, Australia',
  // USA
  'San Francisco, USA',
  'New York, USA',
  'Los Angeles, USA',
  'Seattle, USA',
  'Austin, USA',
  'Boston, USA',
  'Chicago, USA',
  'Miami, USA',
  'Denver, USA',
  'Atlanta, USA',
  // UK
  'London, UK',
  'Manchester, UK',
  'Birmingham, UK',
  'Edinburgh, UK',
  'Bristol, UK',
  // Europe
  'Berlin, Germany',
  'Munich, Germany',
  'Amsterdam, Netherlands',
  'Paris, France',
  'Stockholm, Sweden',
  'Oslo, Norway',
  'Copenhagen, Denmark',
  'Zurich, Switzerland',
  'Dublin, Ireland',
  'Lisbon, Portugal',
  'Barcelona, Spain',
  'Madrid, Spain',
  'Warsaw, Poland',
  'Vienna, Austria',
  // Asia
  'Singapore',
  'Tokyo, Japan',
  'Seoul, South Korea',
  'Hong Kong',
  'Shanghai, China',
  'Beijing, China',
  'Shenzhen, China',
  'Bangalore, India',
  'Mumbai, India',
  'Delhi, India',
  'Hyderabad, India',
  'Hanoi, Vietnam',
  'Ho Chi Minh City, Vietnam',
  'Bangkok, Thailand',
  'Jakarta, Indonesia',
  'Kuala Lumpur, Malaysia',
  'Manila, Philippines',
  'Taipei, Taiwan',
  // Middle East
  'Dubai, UAE',
  'Tel Aviv, Israel',
  'Riyadh, Saudi Arabia',
  // Canada
  'Toronto, Canada',
  'Vancouver, Canada',
  'Montreal, Canada',
  'Calgary, Canada',
  // Latin America
  'São Paulo, Brazil',
  'Buenos Aires, Argentina',
  'Mexico City, Mexico',
  'Bogotá, Colombia',
  'Santiago, Chile',
  // Africa
  'Cape Town, South Africa',
  'Johannesburg, South Africa',
  'Lagos, Nigeria',
  'Nairobi, Kenya',
  // New Zealand
  'Auckland, New Zealand',
  'Wellington, New Zealand',
  'Christchurch, New Zealand',
  // Remote
  'Remote',
];
